// Write a self-contained HTML report to disk (ADR-0005 / ADR-0006).
//
// Given the captured event stream + metadata, call buildReport to produce the
// offline HTML string, then write it under `outDir`. Files are namespaced by
// `cid` (the adapter's worker/project id — e.g. the WDIO capability id or the
// Playwright project name) so parallel workers never collide (ADR-0006 action
// item #6). Lives in @tracelane/report so every adapter (WDIO, Playwright)
// shares one write path.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { eventWithTime } from '@cubenest/rrweb-core';
import { buildReport } from './build-report.js';
import type { ReportMeta } from './types.js';

/** Inputs for {@link writeReport}. */
export interface WriteReportInput {
  /** Output directory (created if missing). */
  outDir: string;
  /** Worker/project id (e.g. WDIO `0-0` or a Playwright project name); namespaces the filename for parallel safety. */
  cid?: string | undefined;
  /** Captured rrweb event stream. */
  events: eventWithTime[];
  /** Report metadata (spec, title, status, error, browser, ...). */
  meta: ReportMeta;
  /** Render the report's "Generated by tracelane" footer. Default true. */
  footer?: boolean | undefined;
}

/**
 * Turn an arbitrary spec path / test title into a filesystem-safe slug:
 * lowercase, non-alphanumerics collapsed to single dashes, trimmed, capped.
 */
export function slugify(input: string): string {
  const slug = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  // Cap length so deeply-nested titles don't blow past filesystem name limits.
  return (slug || 'report').slice(0, 120);
}

/**
 * Build a unique-ish report filename: `<spec>--<title>--<cid>-<ts>.html`. The
 * timestamp + cid keep retries and parallel workers from overwriting each other.
 */
export function reportFileName(meta: ReportMeta, cid?: string): string {
  const specPart = meta.spec ? specSlug(meta.spec) : 'spec';
  const titlePart = slugify(meta.title);
  const cidPart = cid ? `${slugify(cid)}-` : '';
  return `${specPart}--${titlePart}--${cidPart}${Date.now()}.html`;
}

/**
 * Slug for the spec segment: take the file's basename (so an absolute path like
 * `/repo/test/login.spec.ts` doesn't bloat the filename), then strip the common
 * test-file suffixes (`.spec.ts`, `.test.mts`, `.e2e.js`, …) so it slugifies to
 * a clean `login`, not `login-spec`.
 */
export function specSlug(spec: string): string {
  const base = spec.replace(/^.*[/\\]/, '');
  return slugify(base.replace(/(\.(spec|test|e2e|cy))?\.[cm]?[jt]sx?$/, ''));
}

/**
 * Build the report HTML and write it under `outDir`, namespaced by `cid`.
 * Returns the absolute-or-relative path written (as `join` produced it).
 */
export function writeReport(input: WriteReportInput): string {
  const { outDir, cid, events, meta, footer } = input;
  const html = buildReport(events, meta, footer === false ? { footer: false } : {});
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }
  const filePath = join(outDir, reportFileName(meta, cid));
  writeFileSync(filePath, html);
  return filePath;
}
