// User-facing options for the Playwright reporter + fixture, and resolveOptions
// which normalizes them into the fully-resolved shape the session consumes.
//
// The option names mirror @tracelane/wdio (mode, outDir, capture.*, security,
// report.footer, drainIntervalMs, cooldownMs, consolePluginOptions) and the env
// contract mirrors @tracelane/core (TRACELANE_MODE) plus the TRACELANE_* bridge
// the reporter sets at startup.
//
// IMPORTANT — the worker-process bridge: the Playwright fixture runs in a
// SEPARATE worker process and reads configuration ONLY from TRACELANE_* env
// vars, which the Reporter (reporter.ts) bridges from its constructor options.
// Env vars are strings, so JSON-serializable options (networkOptions,
// consolePluginOptions) cross as JSON; FUNCTION-valued options (e.g. a network
// `maskRequestFn` / `maskResponseFn`) CANNOT cross this boundary and are NOT
// supported via reporter config — see the JSDoc on `capture.networkOptions`.

import type { NetworkRecordOptions } from '@cubenest/rrweb-core';
import type { ConsolePluginOptions, Mode } from '@tracelane/core';

/** The default output directory for reports (matches @tracelane/wdio). */
export const DEFAULT_OUT_DIR = './tracelane-reports';

type EnvLike = Record<string, string | undefined>;

/** Which capture channels are enabled (mirrors @tracelane/wdio §M.1). */
export interface CaptureOptions {
  /** Record the rrweb session. Default `true`. When `false`, no recorder starts and no report is written. */
  rrweb?: boolean;
  /**
   * Capture network requests. Default `true`. Supersedes the deprecated
   * top-level {@link TraceLaneOptions.captureNetwork}. Captured in-page by the
   * framework-agnostic `rrweb/network@1` plugin (all browsers, no CDP); on
   * Chromium CDP additionally enriches failed responses.
   */
  network?: boolean;
  /** Capture `console.*` via the rrweb console plugin. Default `true`. */
  console?: boolean;
  /**
   * Options forwarded to the in-page rrweb network plugin
   * (`getRecordNetworkPlugin`): `recordHeaders`, `recordBody`,
   * `payloadHostDenyList`, etc. Defaults are privacy-first (headers + bodies
   * off). Ignored when {@link network} is `false`.
   *
   * LIMITATION (worker-process bridge): function-valued props
   * (`maskRequestFn`, `maskResponseFn`) are NOT supported via reporter config.
   * The reporter bridges this object to the fixture as a JSON string, and
   * functions cannot survive `JSON.stringify` / an env var — they are dropped
   * silently. Use only JSON-serializable masking options here.
   */
  networkOptions?: NetworkRecordOptions;
}

/** User-supplied options (all optional; passed to the reporter and/or fixture). */
export interface TraceLaneOptions {
  /**
   * Capture mode (ADR-0005). `'failed'` (default) writes a report only on test
   * failure; `'all'` writes one for every test. `TRACELANE_MODE` overrides this.
   */
  mode?: Mode;
  /** Directory to write reports into. Default `'./tracelane-reports'`. `TRACELANE_OUT_DIR` overrides. */
  outDir?: string;
  /**
   * Capture network requests. Default `true`.
   *
   * @deprecated Use {@link CaptureOptions.network} (`capture: { network }`)
   * instead. Kept for back-compat; `capture.network` wins when both are set.
   *
   * Captured in-page by the framework-agnostic `rrweb/network@1` plugin, which
   * works on ALL browsers (Chromium/Firefox/WebKit) with no CDP. On Chromium,
   * CDP additionally enriches the report with authoritative status for failed
   * responses and true no-response failures (the report merges the two). Set
   * `false` to disable network capture entirely (both channels).
   *
   * The reporter bridges this option to `TRACELANE_CAPTURE_NETWORK` at startup
   * (only when that env var is not already set), so the fixture honors it. An
   * explicit `TRACELANE_CAPTURE_NETWORK` env var always wins over this option.
   */
  captureNetwork?: boolean;
  /** Per-channel capture toggles (rrweb / network / console) + network masking. */
  capture?: CaptureOptions;
  /**
   * Advisory security-hygiene signals in the report. Default `true`. Set
   * `false` to disable both the `[tracelane.sec]` capture and the report-side
   * analysis. Bridged via `TRACELANE_SECURITY` (`'false'` disables).
   */
  security?: boolean;
  /** Report-output tweaks. */
  report?: {
    /** Render the report's "Generated by tracelane" footer. Default `true`. */
    footer?: boolean;
  };
  /** Node-side drain poll interval in ms (ADR-0006). Default from @tracelane/core when unset. */
  drainIntervalMs?: number;
  /** Re-injection cooldown guard in ms (ADR-0006). Default from @tracelane/core when unset. */
  cooldownMs?: number;
  /**
   * Options forwarded to the in-page rrweb console plugin. Bridged to the
   * fixture as a JSON string, so only JSON-serializable props survive.
   */
  consolePluginOptions?: ConsolePluginOptions;
}

/** Fully-resolved options — every always-present field present. */
export interface ResolvedOptions {
  mode: Mode;
  outDir: string;
  captureNetwork: boolean;
  captureRrweb: boolean;
  captureConsole: boolean;
  security: boolean;
  footer: boolean;
  drainIntervalMs?: number;
  cooldownMs?: number;
  networkOptions?: NetworkRecordOptions;
  consolePluginOptions?: ConsolePluginOptions;
}

function isMode(value: string | undefined): value is Mode {
  return value === 'failed' || value === 'all';
}

/** Read `process.env` defensively (no hard `@types/node` dependency). */
function defaultEnv(): EnvLike {
  return (globalThis as { process?: { env?: EnvLike } }).process?.env ?? {};
}

/** True unless the env var is present and (case-insensitively) `'false'`. */
function envDisables(value: string | undefined): boolean {
  return value !== undefined && value.toLowerCase() === 'false';
}

/**
 * Resolve a boolean channel toggle: an env var (`'false'` disables, anything
 * else enables) wins over the option, which defaults to `true`.
 */
function resolveBoolChannel(envValue: string | undefined, optValue: boolean | undefined): boolean {
  if (envValue !== undefined) return envValue.toLowerCase() !== 'false';
  return optValue ?? true;
}

/** Parse an integer env var; return undefined for missing / NaN values. */
function parseIntEnv(value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  const n = Number.parseInt(value, 10);
  return Number.isNaN(n) ? undefined : n;
}

/** Parse a JSON env var into an object; return undefined on parse failure. */
function parseJsonEnv<T>(value: string | undefined): T | undefined {
  if (value === undefined) return undefined;
  try {
    return JSON.parse(value) as T;
  } catch {
    return undefined;
  }
}

/**
 * Resolve user options into a fully-resolved shape, applying defaults and the
 * `TRACELANE_*` env overrides (env wins over config, matching @tracelane/core's
 * resolveMode). An invalid `TRACELANE_MODE` is ignored. `env` is injectable for
 * testing.
 *
 * Env overrides:
 *   - `TRACELANE_MODE`, `TRACELANE_OUT_DIR`
 *   - `TRACELANE_CAPTURE_NETWORK` (`'false'` disables both the in-page plugin and
 *     the Chromium CDP enrichment) / `_RRWEB` / `_CONSOLE` (`'false'` disables)
 *   - `TRACELANE_SECURITY`, `TRACELANE_FOOTER` (`'false'` disables)
 *   - `TRACELANE_DRAIN_INTERVAL_MS`, `TRACELANE_COOLDOWN_MS` (parsed int; NaN ignored)
 *   - `TRACELANE_NETWORK_OPTIONS`, `TRACELANE_CONSOLE_OPTIONS` (JSON; bad JSON → undefined)
 */
export function resolveOptions(
  opts: TraceLaneOptions = {},
  env: EnvLike = defaultEnv(),
): ResolvedOptions {
  const mode: Mode = isMode(env.TRACELANE_MODE) ? env.TRACELANE_MODE : (opts.mode ?? 'failed');
  const outDir = env.TRACELANE_OUT_DIR ?? opts.outDir ?? DEFAULT_OUT_DIR;

  // Network-on: env wins; else capture.network ?? legacy captureNetwork ?? true.
  const envCaptureNetwork = env.TRACELANE_CAPTURE_NETWORK;
  const captureNetwork =
    envCaptureNetwork !== undefined
      ? envCaptureNetwork.toLowerCase() !== 'false'
      : (opts.capture?.network ?? opts.captureNetwork ?? true);

  const captureRrweb = resolveBoolChannel(env.TRACELANE_CAPTURE_RRWEB, opts.capture?.rrweb);
  const captureConsole = resolveBoolChannel(env.TRACELANE_CAPTURE_CONSOLE, opts.capture?.console);

  const security = envDisables(env.TRACELANE_SECURITY)
    ? false
    : env.TRACELANE_SECURITY !== undefined
      ? true
      : (opts.security ?? true);

  const footer = envDisables(env.TRACELANE_FOOTER)
    ? false
    : env.TRACELANE_FOOTER !== undefined
      ? true
      : (opts.report?.footer ?? true);

  const drainIntervalMs = parseIntEnv(env.TRACELANE_DRAIN_INTERVAL_MS) ?? opts.drainIntervalMs;
  const cooldownMs = parseIntEnv(env.TRACELANE_COOLDOWN_MS) ?? opts.cooldownMs;

  // JSON-serializable masking options: env (JSON) wins over the option.
  const networkOptions =
    parseJsonEnv<NetworkRecordOptions>(env.TRACELANE_NETWORK_OPTIONS) ??
    opts.capture?.networkOptions;
  const consolePluginOptions =
    parseJsonEnv<ConsolePluginOptions>(env.TRACELANE_CONSOLE_OPTIONS) ?? opts.consolePluginOptions;

  const resolved: ResolvedOptions = {
    mode,
    outDir,
    captureNetwork,
    captureRrweb,
    captureConsole,
    security,
    footer,
  };
  if (drainIntervalMs !== undefined) resolved.drainIntervalMs = drainIntervalMs;
  if (cooldownMs !== undefined) resolved.cooldownMs = cooldownMs;
  if (networkOptions !== undefined) resolved.networkOptions = networkOptions;
  if (consolePluginOptions !== undefined) resolved.consolePluginOptions = consolePluginOptions;
  return resolved;
}
