// User-facing options for the WDIO Service / hook factory (P1 PRD §M.1).

import type { NetworkRecordOptions } from '@cubenest/rrweb-core';
import type { ConsolePluginOptions, Mode } from '@tracelane/core';

/** Which capture channels are enabled (P1 PRD §M.1). */
export interface CaptureOptions {
  /** Record the rrweb session. Default true. */
  rrweb?: boolean;
  /**
   * Capture network requests. Default `true`.
   *
   * When enabled (default), the in-page rrweb network plugin
   * (`rrweb/network@1`) is registered alongside the recorder —
   * framework-agnostic, no CDP required, works on all browsers. The
   * legacy CDP-based path is preserved as a fallback but no longer the
   * primary capture mechanism.
   *
   * Privacy defaults (inherited from `@cubenest/rrweb-core`): headers and
   * bodies are NOT captured unless opted in via {@link networkOptions}.
   * Because the fetch/XHR wrappers are gated behind `recordHeaders` /
   * `recordBody` (both off by default), the DEFAULT capture surface is
   * PerformanceObserver timing only. That has two consequences worth
   * knowing:
   *   - method and an accurate per-request status may be unavailable
   *     (PerformanceObserver entries don't carry the request method, and
   *     report `status` only on same-origin / Timing-Allow-Origin
   *     responses);
   *   - cross-origin sub-resources report `status: 0` per the Resource
   *     Timing spec even though they loaded fine — these are NOT treated
   *     as failures by the report.
   * Enable the wrappers (and thus accurate per-request method + status,
   * plus optional headers/bodies) via {@link networkOptions}. The CDP
   * fallback, when present, separately supplies authoritative status and
   * true no-response failures.
   */
  network?: boolean;
  /** Capture `console.*` via the rrweb console plugin. Default true. */
  console?: boolean;
  /**
   * Options forwarded to the in-page rrweb network plugin
   * (`getRecordNetworkPlugin`). The full surface from
   * `@cubenest/rrweb-core` is exposed: `recordHeaders`, `recordBody`,
   * `maskRequestFn`, `payloadHostDenyList`, etc. Defaults are the
   * plugin's defaults (privacy-first — headers + bodies off).
   *
   * Ignored when {@link network} is `false`.
   */
  networkOptions?: NetworkRecordOptions;
}

/** Options for {@link TraceLaneService} and {@link traceLaneHooks} (P1 PRD §M.1). */
export interface TraceLaneOptions {
  /**
   * Capture mode (ADR-0005). `'failed'` (default) writes a report only on test
   * failure; `'all'` writes one for every test. The `TRACELANE_MODE` env var
   * overrides this at report-decision time.
   */
  mode?: Mode;
  /** Directory to write reports into. Default `'./tracelane-reports'`. */
  outDir?: string;
  /** Reserved for the v1.1 Allure shim (ADR-0004). No-op in v1. Default false. */
  allure?: boolean;
  /** Per-channel capture toggles. */
  capture?: CaptureOptions;
  /** Reserved for the post-MVP visual-diff add-on (P1 PRD §H). No-op in v1. */
  visualDiff?: boolean;
  /** Node-side drain poll interval in ms (ADR-0006). Default 500 (from @tracelane/core when unset). */
  drainIntervalMs?: number;
  /** Re-injection cooldown guard in ms (ADR-0006). Default 250. */
  cooldownMs?: number;
  /** Options forwarded to the in-page rrweb console plugin. */
  consolePluginOptions?: ConsolePluginOptions;
  /** Advisory security-hygiene signals in the report (default true). Set false to disable capture + analysis. */
  security?: boolean;
  /**
   * Report-output tweaks.
   *
   * - `footer` — render the self-contained report's "Generated by tracelane"
   *   footer. Default `true`. Set `false` to suppress it (e.g. when embedding
   *   reports in an internal tool where the attribution isn't wanted).
   */
  report?: {
    /** Render the report footer. Default `true`. */
    footer?: boolean;
  };
}

/** The default output directory for reports. */
export const DEFAULT_OUT_DIR = './tracelane-reports';
